-- create_tables.sql
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE COUNTRIES (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        cities CLOB,
        largest_city VARCHAR2(255)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
