package com.example.jarkataee.dao;

import com.example.jarkataee.config.DatabaseConfig;
import com.example.jarkataee.domain.City;
import com.example.jarkataee.domain.Country;

import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CountryDaoImpl implements CountryDao {


    public void createTableIfNotExists() throws SQLException {
        try (Connection conn = DatabaseConfig.getConnection();
             Statement stmt = conn.createStatement()) {

            ResultSet countryTableCheck = conn.getMetaData().getTables(null, null, "COUNTRIES", null);

            if (!countryTableCheck.next()) {
                String createCountryTableSQL = "CREATE TABLE countries (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "name VARCHAR2(100) UNIQUE NOT NULL, " +
                        "cities VARCHAR2(1000), " +
                        "largest_city VARCHAR2(100)" +
                        ")";
                stmt.executeUpdate(createCountryTableSQL);
                System.out.println("Table 'countries' created successfully.");
            } else {
                System.out.println("Table 'countries' already exists.");
            }
        }
    }


//    public void createTableIfNotExists() throws SQLException {
//        try (Connection conn = DatabaseConfig.getConnection();
//             Statement stmt = conn.createStatement()) {
//
//            // Create 'countries' table if not exists
//            ResultSet countryTableCheck = conn.getMetaData().getTables(null, null, "COUNTRIES", null);
//
//            if (!countryTableCheck.next()) {
//                String createCountryTableSQL = "CREATE TABLE countries (" +
//                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
//                        "name VARCHAR2(100) UNIQUE NOT NULL, " +
//                        "largest_city VARCHAR2(100)" +
//                        ")";
//                stmt.executeUpdate(createCountryTableSQL);
//                System.out.println("Table 'countries' created successfully.");
//            } else {
//                System.out.println("Table 'countries' already exists.");
//            }
//
//            // Create 'cities' table with foreign key if not exists
//            ResultSet cityTableCheck = conn.getMetaData().getTables(null, null, "CITIES", null);
//
//            if (!cityTableCheck.next()) {
//                String createCityTableSQL = "CREATE TABLE cities (" +
//                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
//                        "name VARCHAR2(100) NOT NULL, " +
//                        "country_id NUMBER, " +
//                        "FOREIGN KEY (country_id) REFERENCES countries(id)" +
//                        ")";
//                stmt.executeUpdate(createCityTableSQL);
//                System.out.println("Table 'cities' created successfully.");
//            } else {
//                System.out.println("Table 'cities' already exists.");
//            }
//        }
//    }


//    public void createTableIfNotExists() throws SQLException {
//        try (Connection conn = DatabaseConfig.getConnection();
//             Statement stmt = conn.createStatement()) {
//
//            ResultSet rs = conn.getMetaData().getTables(null, null, "CITIES", null);
//
//            if (!rs.next()) {
//                String createTableSQL = "CREATE TABLE cities (" +
//                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
//                        "name VARCHAR2(100), " +
//                        "population NUMBER, " +
//                        "country_name VARCHAR2(100)" +
//                        ")";
//                stmt.executeUpdate(createTableSQL);
//                System.out.println("Table 'cities' created successfully.");
//            } else {
//                System.out.println("Table 'cities' already exists.");
//            }
//        }
//    }


    public Country getCountryByName(String name) throws SQLException {
        try (Connection conn = DatabaseConfig.getConnection()) {
            String query = "SELECT * FROM countries WHERE name = ?";

            try (PreparedStatement stmt = conn.prepareStatement(query)) {
                stmt.setString(1, name);
                ResultSet rs = stmt.executeQuery();

                if (rs.next()) {
                    String countryName = rs.getString("name");
                    String cityString = rs.getString("cities");  // Comma-separated cities
                    List<String> cities = Arrays.asList(cityString.split(", "));
                    String largestCity = rs.getString("largest_city");

                    return new Country(countryName, cities, largestCity);
                }
            }
        }
        return null;
    }


    public List<String> getCitiesByCountry(String countryName) throws SQLException {
        // Query to get the cities column from the countries table
        String query = "SELECT cities FROM countries WHERE name = ?";
        List<String> cities = new ArrayList<>();

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {
            // Set the country name parameter
            stmt.setString(1, countryName);
            ResultSet rs = stmt.executeQuery();

            // Retrieve the cities string and split it into a list
            if (rs.next()) {
                String citiesString = rs.getString("cities");  // Assuming cities are stored as a comma-separated string
                if (citiesString != null && !citiesString.isEmpty()) {
                    cities = Arrays.asList(citiesString.split(",\\s*"));  // Split on commas and trim spaces
                }
            }
        }

        return cities;  // Return the list of city names
    }


    @Override
    public void saveCountry(Country country) throws SQLException {
        try (Connection conn = DatabaseConfig.getConnection()) {
            String insertCountrySQL = "INSERT INTO countries (name, cities, largest_city) VALUES (?, ?, ?)";

            try (PreparedStatement stmt = conn.prepareStatement(insertCountrySQL)) {
                stmt.setString(1, country.getName());
                stmt.setString(2, String.join(", ", country.getCities()));  // Convert the list of cities to a comma-separated string
                stmt.setString(3, country.getLargestCity());
                stmt.executeUpdate();
            }
        }
    }



    @Override
    public void saveCities(List<City> cities) {
        String query = "INSERT INTO cities (name, population, country_name) VALUES (?, ?, ?)";

        try (Connection conn = DatabaseConfig.getConnection();
             PreparedStatement stmt = conn.prepareStatement(query)) {

            // Disable auto-commit for batch processing
            conn.setAutoCommit(false);

            for (City city : cities) {
                stmt.setString(1, city.getCityName());
                stmt.addBatch(); // Add this insert to the batch
            }

            // Execute batch insert
            stmt.executeBatch();

            // Commit transaction
            conn.commit();
        } catch (SQLException e) {
            System.err.println("Error inserting cities: " + e.getMessage());
        }
    }


    public void saveCity(City city) throws SQLException {
        try (Connection conn = DatabaseConfig.getConnection()) {
            String insertCitySQL = "INSERT INTO cities (name) VALUES (?, ?)";

            try (PreparedStatement cityStmt = conn.prepareStatement(insertCitySQL)) {
                cityStmt.setString(1, city.getCityName());
                cityStmt.executeUpdate();
            }
        }
    }





    @Override
    public String getLargestCityFromDbOrApi(String country) {
        return null;
    }
}
